from enzymetk import Chai
from enzymetk import Save
import pandas as pd

output_dir = './'
num_threads = 1
id_col = 'Entry'
seq_col = 'Sequence'
substrate_col = 'Substrate'
rows = [['P0019', 'MKIGSGEKLLFIGDSITDCGRARPEGEGSFGALGTGYVAYVVGLLQAVYPELGIRVVNKGISGNTVRDLKARWEEDVIAQKPDWVSIMIGINDVWRQYDLPFMKEKHVYLDEYEATLRSLVLETKPLVKGIILMTPFYIEGNEQDPMRRTMDQYGRVVKQIAEETNSLFVDTQAAFNEVLKTLYPAALAWDRVHPSVAGHMILARAFLREIGFEWVRSR', 'CC1=CC(=O)OC2=C1C=CC(=C2)OC(=O)C', ''], 
        ['P0020', 'MEKEIFYDSDGAKIRAFLATPENPKLAVIVIHEIWGLNDNIKDISRRLANEGYMALAPQLYTRNEDVLNEGNIQNVMMKVWSIPPEKRNDPNSYQQIMSALDEKGKKVAELLVLNRQKTEEQMIKDAIKAYEYVSSQGVKKIVSMGFCMGGGLAFQLATEVPLDGTIVFYGRNPQPLEAIQKIKGPILGLYAGEDPPIDAGLPDLISAIIKYKKDLELKIYPGAYHAFFNDRGRSYNKEAAEDAWERVKSFLRRVSK', 'CC1=CC(=O)OC2=C1C=CC(=C2)OC(=O)C', ''],
        ['P0040', 'MPSPRRNPIRVQHLTLLVFSHGWSGFRSQSTFLLQELASHGYVVASVDHPYDAAFVIFPDGRAIYNDPDVLGADGPDFEQRRNQLVRTRAADVGLAIDELEQVASGDSVLNGLIDFGRIGVFGHSTGGGTVIEFCGTDERCTAALGLDTWAEPVSDSVIESGLSQPLFMQFSQLWPWAANTTRVEHLLRQQF', 'CC1=CC(=O)OC2=C1C=CC(=C2)OC(=O)C', ''],
        ['P0007', 'MKIVPPKPFFFEAGERAVLLLHGFTGNSADVRMLGRFLESKGYTCHAPIYKGHGVPPEELVHTGPDDWWQDVMNGYEFLKNKGYEKIAVAGLSLGGVFSLKLGYTVPIEGIVTMCAPMYIKSEETMYEGVLEYAREYKKREGKSEEQIEQEMEKFKQTPMKTLKALQELIADVRDHLDLIYAPTFVVQARHDEMINPDSANIIYNEIESPVKQIKWYEQSGHVITLDQEKDQLHEDIYAFLESLDWLEHHHHHH', 'CC1=CC(=O)OC2=C1C=CC(=C2)OC(=O)C', ''],
        ['P0008', 'MKIVPPKPFLFEAGERAVLLLHGFTGNSADVRMLGRFLESKGYTCHAPIYKGHGVPPEELVHTGPDDWWQDVMNGYEFLKNKGYEKIAVAGLSLGGVFSLKLGYTVPIEGIVTMCAPMYIKSEETVYEGVLEYAREYKKREGKSEEQIEQEMEEFKQTPMKTLKALQELIADVRDHLDLIYAPTFVVQARHDEMINPDSANIIYNEIESPVKQIKWYEQSGHVITLDQEKDQLHEDIYAFLESLDWLEHHHHHH', 'CC1=CC(=O)OC2=C1C=CC(=C2)OC(=O)C', ''],
        ['P0009', 'MKIVPPKPFFFEAGERAVLLLHGFTGNSADVRMLGRFLESKGYTCHAPIYKGHGVPPEELVHTGPDDWWQDVMNGYEFLKNKGYEKIAVAGLSLGGVFSLKLGYTVPIEGIVTMCAPMYIKSEETMYEGVLEYAREYKKREGKSEEQIEQEMEKFKQTPMKTLKALQELIADVRDHLDLIYAPTFVVQARHDGMINPDSANIIYNEIESPVKQIKWYEQSGHVITLDQEKDQLHEDIYAFLESLDWLEHHHHHH', 'CC1=CC(=O)OC2=C1C=CC(=C2)OC(=O)C', ''],
        ['P0010', 'MKIVPPKPFFFEAGERAVLLLHGFTGNSADVRMLGRFLESKGYTCHAPIYKGHGVPPEELVHTGPDDWWQDVMNGYEFLKNKGYEKIAVAGLSLGGVFSLKLGYTVPIEGIVTMCAPMYIKSEETMYEGVLEYAREYEKREGKSEEQIEQEMEKFKQTPMKTLKALQELIADVRDHLGLIYAPTFVVQARHDEMINPDSANIIYNEIESPVKQIKWYEQSGHVITLDQEKDQLHEGIYAFLESLDWLEHHHHHH', 'CC1=CC(=O)OC2=C1C=CC(=C2)OC(=O)C', ''],
        ['P0011', 'MKIVPPKPFFFEAGERAVLLLHGFTGNSADVRMLGRFLESKGYTCHAPIYKGHGVPPEELVHTGPDDWWQDVMNGYEFLKNKGYEKIAVAGLSLGGVLSLKLGYTVPIEGIVTMCAPMYIKSEETMYEGVLEYAREYKKREGKSEELIDQEMEKFKQTPMKTLKALQKLIADVRDHLDLIYAPTFVAQARRDEMINPDSANIIYNEIESPVKQIKWYEQSGHVITLDQEKDQLHEDIYAFLESLDWLEHHHHHH', 'CC1=CC(=O)OC2=C1C=CC(=C2)OC(=O)C', '']

        ]
df = pd.DataFrame(rows, columns=[id_col, seq_col, substrate_col, 'cofactor'], )
print(df)
 # id_col: str, seq_col: str, substrate_col: str, cofactor_col: str, output_dir: str, 
df = df << (Chai(id_col, seq_col, substrate_col, 'cofactor', f'prelim_data/', num_threads) >> Save(f'prelim_data/prelim_data.pkl'))
print(df)